### ISSUE TITLE
BUG: Application installs under the name "Tripleblind"

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/mobileapp#10]
The icon needs to get the name of the app "Safe Paths".  (At least that is the working name for now)

**Comment by vitorpamplona** [comment]
Fixed for Android. Committed to the development Branch. I have not touched the iOS project files.

**Comment by nic-rodriguez** [comment]
Fixed for ios, pull request sent for namefix branch

**Comment by penrods** [comment]
Fixed by #11
